/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanIFTicateur.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Alexandre
 */
public class MainWindow extends javax.swing.JFrame {

    public Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    public Dimension coordonnePanelInformation;
    public Dimension coordonnePanelOption;

    public Dimension getCoordonnePanelInformation() {
        return coordonnePanelInformation;
    }

    public void setCoordonnePanelInformation(int a, int b) {
        coordonnePanelInformation = new Dimension(a / 4, b);
    }

    /**
     * Creates new form PlanIFTicateur
     */
    public MainWindow() {
        coordonnePanelInformation = new Dimension(screenSize.width * 2 / 7, screenSize.height);
        coordonnePanelOption = new Dimension(screenSize.width, screenSize.height / 5);

        initComponents();
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent e) {
                setExtendedState(MAXIMIZED_BOTH);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFenetre = new javax.swing.JPanel();
        panelInformation = new javax.swing.JPanel();
        panelAutre = new javax.swing.JPanel();
        panelActivite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeCours = new javax.swing.JList();
        panelPrincipale = new javax.swing.JPanel();
        panelOption = new javax.swing.JPanel();
        panelGrille = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuOption = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemNouveau = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemEcraser = new javax.swing.JMenuItem();
        menuItemSauvegarder = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().setLayout(new java.awt.BorderLayout(25, 25));

        panelFenetre.setBackground(new java.awt.Color(204, 0, 0));
        panelFenetre.setLayout(new java.awt.BorderLayout(25, 25));

        panelInformation.setBackground(new java.awt.Color(0, 0, 153));
        panelInformation.setPreferredSize(getCoordonnePanelInformation());
        panelInformation.setLayout(new java.awt.BorderLayout(25, 25));

        panelAutre.setPreferredSize(coordonnePanelOption);

        javax.swing.GroupLayout panelAutreLayout = new javax.swing.GroupLayout(panelAutre);
        panelAutre.setLayout(panelAutreLayout);
        panelAutreLayout.setHorizontalGroup(
            panelAutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelAutreLayout.setVerticalGroup(
            panelAutreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelInformation.add(panelAutre, java.awt.BorderLayout.PAGE_END);

        panelActivite.setLayout(new javax.swing.BoxLayout(panelActivite, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("Liste de Cours (LABEL À CHANGER)");
        panelActivite.add(jLabel1);

        listeCours.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeCours.setPreferredSize(new java.awt.Dimension(200, 0));
        jScrollPane1.setViewportView(listeCours);

        panelActivite.add(jScrollPane1);

        panelInformation.add(panelActivite, java.awt.BorderLayout.WEST);

        panelFenetre.add(panelInformation, java.awt.BorderLayout.LINE_END);

        panelPrincipale.setBackground(new java.awt.Color(0, 153, 0));
        panelPrincipale.setLayout(new java.awt.BorderLayout(25, 25));

        panelOption.setPreferredSize(coordonnePanelOption);

        javax.swing.GroupLayout panelOptionLayout = new javax.swing.GroupLayout(panelOption);
        panelOption.setLayout(panelOptionLayout);
        panelOptionLayout.setHorizontalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        panelOptionLayout.setVerticalGroup(
            panelOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelPrincipale.add(panelOption, java.awt.BorderLayout.PAGE_END);

        jLabel2.setText("Grille de cours");

        javax.swing.GroupLayout panelGrilleLayout = new javax.swing.GroupLayout(panelGrille);
        panelGrille.setLayout(panelGrilleLayout);
        panelGrilleLayout.setHorizontalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrilleLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(875, Short.MAX_VALUE))
        );
        panelGrilleLayout.setVerticalGroup(
            panelGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrilleLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        panelPrincipale.add(panelGrille, java.awt.BorderLayout.CENTER);

        panelFenetre.add(panelPrincipale, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFenetre, java.awt.BorderLayout.CENTER);

        menuOption.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuOption.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        menuOption.setPreferredSize(new java.awt.Dimension(180, 40));

        jMenu1.setText("Fichier");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuItemNouveau.setText("Nouveau");
        menuItemNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNouveauActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNouveau);
        jMenu1.add(jSeparator1);

        menuItemEcraser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemEcraser.setText("Sauvegarde");
        menuItemEcraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEcraserActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEcraser);

        menuItemSauvegarder.setText("Sauvegarder sous");
        jMenu1.add(menuItemSauvegarder);
        jMenu1.add(jSeparator2);

        menuItemQuitter.setText("Quitter");
        menuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemQuitter);

        menuOption.add(jMenu1);

        jMenu2.setText("Option");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuOption.add(jMenu2);
        menuOption.add(jMenu3);

        jMenu4.setText("Windows");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setText("Statistique");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        menuOption.add(jMenu4);

        setJMenuBar(menuOption);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNouveauActionPerformed
        JFileChooser dialogue = new JFileChooser(new File("/"));
        File fichier;

        if (dialogue.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            fichier = dialogue.getSelectedFile();
            System.out.println(fichier.getAbsolutePath());
        }
    }//GEN-LAST:event_menuItemNouveauActionPerformed

    private void menuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuitterActionPerformed

        System.exit(0);
    }//GEN-LAST:event_menuItemQuitterActionPerformed

    private void menuItemEcraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEcraserActionPerformed

    }//GEN-LAST:event_menuItemEcraserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JList listeCours;
    private javax.swing.JMenuItem menuItemEcraser;
    private javax.swing.JMenuItem menuItemNouveau;
    private javax.swing.JMenuItem menuItemQuitter;
    private javax.swing.JMenuItem menuItemSauvegarder;
    private javax.swing.JMenuBar menuOption;
    private javax.swing.JPanel panelActivite;
    private javax.swing.JPanel panelAutre;
    private javax.swing.JPanel panelFenetre;
    private javax.swing.JPanel panelGrille;
    private javax.swing.JPanel panelInformation;
    private javax.swing.JPanel panelOption;
    private javax.swing.JPanel panelPrincipale;
    // End of variables declaration//GEN-END:variables
}
